// Code generated by MockGen. DO NOT EDIT.
// Source: ../authorization_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// MockAuthorizationHandler is a mock of AuthorizationHandler interface.
type MockAuthorizationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationHandlerMockRecorder
}

// MockAuthorizationHandlerMockRecorder is the mock recorder for MockAuthorizationHandler.
type MockAuthorizationHandlerMockRecorder struct {
	mock *MockAuthorizationHandler
}

// NewMockAuthorizationHandler creates a new mock instance.
func NewMockAuthorizationHandler(ctrl *gomock.Controller) *MockAuthorizationHandler {
	mock := &MockAuthorizationHandler{ctrl: ctrl}
	mock.recorder = &MockAuthorizationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationHandler) EXPECT() *MockAuthorizationHandlerMockRecorder {
	return m.recorder
}
